#pragma once

enum class Topic {
    WS_SEND,
    PICTURE,
    CLEAR_IMAGES,
    CLEAR_DISPLAY,
    IMAGE_REMOVED,
    IMAGE_NEW,
    SKIP_IMAGE,
    UPDATE_DISPLAY_INTERVAL,
    SET_SLIDESHOW_ACTIVE,
};
